version: '3.8'  # Specify the Docker Compose version

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Optional if your file is named 'Dockerfile'
    ports:
      - "8000:8000"
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Optional if your file is named 'Dockerfile'
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
